import { execFile } from "node:child_process";
import { promisify } from "node:util";
import {
  type DiffPrecisionSummary,
  isAgentArenaGeneratedPath,
  logger,
  metrics,
  type TaskChangePolicy,
  uniqueSorted
} from "@agentarena/core";
import picomatch from "picomatch";

const execFileAsync = promisify(execFile);

/**
 * Tagged result of attempting to enumerate changed files.
 *
 * When `reliable: false`, downstream consumers (diff precision, scoring) must
 * skip metrics derived from `files` — empty `files` here means "unknown",
 * NOT "no changes". This distinction is the difference between an unscored run
 * and a zero-scored run, which directly affects benchmark fairness.
 */
/**
 * @see {@link ChangedFilesHintResult} in packages/adapters/src/adapter-helpers.ts — identical shape, kept separate to avoid cross-package import.
 */
export interface ChangedFilesResult {
  files: string[];
  reliable: boolean;
  /** Reason the result is unreliable; only present when `reliable === false`. */
  reason?: string;
}

const GIT_DIFF_TIMEOUT_MS = 10_000;

// Files generated by AgentArena tooling — not agent changes, should not penalize diff precision.
const DIFF_IGNORE_PATTERNS = [
  ".aa-evidence/**",
  "agent-stdout.jsonl",
  "agent-stderr.log",
  "prompt.txt",
  ".claude/**",
];

const diffIgnoreMatchers = DIFF_IGNORE_PATTERNS.map((p) => picomatch(p, { dot: true }));

function isToolGeneratedFile(filePath: string): boolean {
  return isAgentArenaGeneratedPath(filePath) || diffIgnoreMatchers.some((isMatch) => isMatch(filePath));
}

export function buildDiffPrecision(
  expectedChangedPaths: string[] | undefined,
  changedFiles: string[],
  options: { reliable?: boolean } = {}
): DiffPrecisionSummary | undefined {
  if (!expectedChangedPaths || expectedChangedPaths.length === 0) {
    return undefined;
  }
  // If the upstream snapshot or git enumeration was unreliable, refuse to score —
  // returning `0` would silently corrupt the composite score with bogus data.
  if (options.reliable === false) {
    return undefined;
  }

  // Filter out tool-generated files before computing precision
  const agentFiles = changedFiles.filter((f) => !isToolGeneratedFile(f));

  const matchers = expectedChangedPaths.map((pattern) => picomatch(pattern, { dot: true }));
  const matchedFiles = agentFiles.filter((filePath) => matchers.some((isMatch) => isMatch(filePath)));
  const unexpectedFiles = agentFiles.filter((filePath) => !matchers.some((isMatch) => isMatch(filePath)));

  return {
    score: agentFiles.length > 0 ? matchedFiles.length / agentFiles.length : 0,
    expectedScopeCount: expectedChangedPaths.length,
    totalChangedFiles: agentFiles.length,
    matchedFiles: uniqueSorted(matchedFiles),
    unexpectedFiles: uniqueSorted(unexpectedFiles)
  };
}

export interface ChangePolicyResult {
  success: boolean;
  reliable: boolean;
  changedFiles: string[];
  unexpectedFiles: string[];
  forbiddenFiles: string[];
  reason: string;
}

/**
 * Enforce task-declared file-scope rules against real snapshot changes.
 * Adapter file hints are intentionally excluded by callers so an adapter
 * cannot make a no-op appear complete.
 */
export function evaluateChangePolicy(
  policy: TaskChangePolicy | undefined,
  changedFiles: string[],
  options: { reliable?: boolean } = {}
): ChangePolicyResult | undefined {
  if (!policy) {
    return undefined;
  }

  const agentFiles = uniqueSorted(changedFiles.filter((filePath) => !isToolGeneratedFile(filePath)));
  if (options.reliable === false) {
    return {
      success: false,
      reliable: false,
      changedFiles: agentFiles,
      unexpectedFiles: [],
      forbiddenFiles: [],
      reason: "The before/after workspace snapshots are unreliable; change scope cannot be verified."
    };
  }

  const allowedMatchers = (policy.allowedPaths ?? []).map((pattern) => picomatch(pattern, { dot: true }));
  const forbiddenMatchers = (policy.forbiddenPaths ?? []).map((pattern) => picomatch(pattern, { dot: true }));
  const unexpectedFiles = allowedMatchers.length > 0
    ? agentFiles.filter((filePath) => !allowedMatchers.some((matches) => matches(filePath)))
    : [];
  const forbiddenFiles = forbiddenMatchers.length > 0
    ? agentFiles.filter((filePath) => forbiddenMatchers.some((matches) => matches(filePath)))
    : [];
  const countTooSmall = policy.minChangedFiles !== undefined && agentFiles.length < policy.minChangedFiles;
  const countTooLarge = policy.maxChangedFiles !== undefined && agentFiles.length > policy.maxChangedFiles;
  const missingChange = policy.requireAgentChange === true && agentFiles.length === 0;
  const reasons: string[] = [];

  if (missingChange) reasons.push("No agent-authored file change was detected.");
  if (unexpectedFiles.length > 0) reasons.push(`Files outside allowedPaths: ${unexpectedFiles.join(", ")}.`);
  if (forbiddenFiles.length > 0) reasons.push(`Forbidden files changed: ${forbiddenFiles.join(", ")}.`);
  if (countTooSmall) reasons.push(`Changed file count ${agentFiles.length} is below minChangedFiles ${policy.minChangedFiles}.`);
  if (countTooLarge) reasons.push(`Changed file count ${agentFiles.length} exceeds maxChangedFiles ${policy.maxChangedFiles}.`);

  return {
    success: reasons.length === 0,
    reliable: true,
    changedFiles: agentFiles,
    unexpectedFiles: uniqueSorted(unexpectedFiles),
    forbiddenFiles: uniqueSorted(forbiddenFiles),
    reason: reasons.length === 0 ? "Changed files satisfy the task change policy." : reasons.join(" ")
  };
}

export async function collectChangedFiles(workspacePath: string): Promise<ChangedFilesResult> {
  const startTime = Date.now();
  let status = "success";
  try {
    const { stdout } = await execFileAsync("git", ["diff", "--name-only", "HEAD"], {
      cwd: workspacePath,
      timeout: GIT_DIFF_TIMEOUT_MS
    });
    return { files: stdout.trim().split("\n").filter(Boolean).filter((file) => !isToolGeneratedFile(file)), reliable: true };
  } catch (error: unknown) {
    status = "failure";
    const stderr = (error instanceof Error && "stderr" in error) ? String((error as NodeJS.ErrnoException & { stderr?: string }).stderr ?? "") : "";
    const rawCode = (error instanceof Error && "code" in error) ? (error as Record<string, unknown>).code : undefined;
    // Not-a-git-repository is a legitimate "no diff information" case, not an error.
    // git exits 128 with stderr like "fatal: not a git repository (or any of the parent directories)".
    // Match case-insensitively so different locales/wrappings still classify correctly.
    const lowerStderr = stderr.toLowerCase();
    if (rawCode === 128 || rawCode === "128" || lowerStderr.includes("not a git repository") || lowerStderr.includes("not a git")) {
      return { files: [], reliable: true };
    }
    const message = error instanceof Error ? error.message : String(error);
    logger.warn("runner", "git.diff_failed", `git diff failed in ${workspacePath}: ${message}`);
    return { files: [], reliable: false, reason: `git diff failed: ${message}` };
  } finally {
    const durationSeconds = (Date.now() - startTime) / 1000;
    metrics.gitOperationTotal.inc({ operation: "diff", status });
    metrics.gitOperationDurationSeconds.observe({ operation: "diff" }, durationSeconds);
  }
}
